model:
  model_id: "qwen_128_sft_en"
  max_model_len: 8192
  gpu_memory_utilization: 0.5

dataset:
  data_dir: "./data/data_en"
  split: "test"
  output_path: "SFT_finqa_test.json"

sampling:
  temperature: 0.6
  top_p: 0.95
  top_k: 20
  max_tokens: 32768
